### ISSUE TITLE
pr

### ISSUE THREAD

**Issue by ghost** [lordmulder/msws-rng#2]
would you mind merging [this](https://github.com/phoebe-leong/msws-rng/tree/pr)? its like a duplicate of this repo with some changes
im sorry i didnt make it a fork but i just wasnt thinking right att or smth idk

**Comment by lordmulder** [comment]
Apparently this was **not** forked from my repo, but is a completely separate repo 😕 

If you want your changes to be reviewed and (possibly) be merged, then first of all create a proper **fork** of the _original_ repo, rather than staring a new repo from the scratch. Then add a clean commit (with proper description!) for each change you make.

It should be clear for each change what it does and why it is needed. Not building up on the original history  and just throwing in "some changes" without an explanation, in the hope that the original author will figure out your intentions, won't work 😨 

Finally, create a proper [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

**Comment by ghost** [comment]
ok ty!
